name: Combined Web and API Tests
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Java for Web Tests
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Run Web Tests
        run: mvn clean test
      - name: Generate Web Allure Report
        run: mvn allure:report
      - name: Upload Web Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: web-allure-report
          path: target/allure-results

      # Setup Python for API Tests
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install API Test Dependencies
        run: |
          cd api_tests
          pip install -r requirements.txt
      - name: Run API Tests
        run: |
          cd api_tests
          pytest test_api.py -v --html=report.html --self-contained-html
      - name: Upload API Test Report
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: api_tests/report.html
